[package]
name = "fisha"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
rfd = "0.11"
eframe = "0.33.0"

[profile.release]
opt-level = "s"
panic = "abort"
strip = true
lto = true
debug = false